openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://ismart.dafabet.com
security:
- x-session: []
paths:
  /Customer/OddsType:
    post:
      operationId: SetOddsType
      parameters:
      - explode: true
        in: query
        name: set
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetOddsTypeResponse'
          description: Ok
      tags:
      - Login
  /balance/GetAccountInfo:
    post:
      operationId: GetAccount
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountResponse'
          description: Ok
      tags:
      - Login
  /statement/GetStatusByTransid:
    post:
      operationId: GetBetStatus
      parameters:
      - explode: true
        in: query
        name: transid
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BetStatusResponse'
          description: Ok
      tags:
      - BetList
  /Running/GetEarly_ch:
    post:
      operationId: GetRunningBetList
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                datatype:
                  example: 0
                  type: integer
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunningBetListResponse'
          description: Ok
      tags:
      - BetList
  /Statement/GetDBetList_ch:
    post:
      operationId: GetSettledBetList
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/x-www-form-urlencoded; charset=UTF-8:
            schema:
              properties:
                fdate:
                  example: 05/17/2020
                  type: string
                datatype:
                  example: 8
                  type: integer
              type: object
        required: true
      responses:
        "200":
          content:
            text/html:
              schema:
                type: string
          description: Ok
      tags:
      - BetList
  /CashOut/Token:
    get:
      operationId: CheckToken
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckTokenResponse'
          description: Ok
      tags:
      - Login
  /Deposit_ProcessLogin.aspx:
    get:
      operationId: ProcessLogin
      parameters:
      - example: en
        explode: true
        in: query
        name: lang
        required: true
        schema:
          type: string
        style: form
      - example: 111111111-1111-1111-1111-f7a3b65c1111
        explode: true
        in: query
        name: st
        required: true
        schema:
          type: string
        style: form
      - description: https://m.dafabet.com/en
        example: https://m.dafabet.com/en
        explode: true
        in: query
        name: homeURL
        required: true
        schema:
          type: string
        style: form
      - description: https://m.dafabet.com/en&OType=01&oddstype=1
        example: https://m.dafabet.com/en&OType=01&oddstype=1
        explode: true
        in: query
        name: extendSessionURL
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            text/html:
              schema:
                type: string
          description: Ok
      tags:
      - Login
  /en/api/plugins/component/route/header_login/authenticate:
    post:
      operationId: Authenticate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthenticateRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateResponse'
          description: Ok
      servers:
      - url: https://m.dafabet.com
      tags:
      - Login
  /{auth_path}Odds/GetMarket:
    post:
      operationId: GetMarkets
      parameters:
      - description: if user logins, there is no BF
        example: BF
        explode: false
        in: path
        name: auth_path
        required: true
        schema:
          example: BF
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowAllOddsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMarketsResponse'
          description: Ok
      tags:
      - Odds
  /GetReferenceData/GetBettypeName:
    get:
      operationId: GetBetTypes
      parameters:
      - example: en-US
        explode: true
        in: query
        name: lang
        required: true
        schema:
          default: en-US
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: Ok
      tags:
      - Odds
  /BetV2/ProcessBet:
    post:
      operationId: PlaceBet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TicketsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceBetRequest'
          description: Ok
      tags:
      - Tickets
  /BetV2/GetTickets:
    post:
      operationId: GetTickets
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TicketsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketsResponse'
          description: Ok
      tags:
      - Tickets
  /balance/UpdateBalance:
    post:
      operationId: GetBalance
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
          description: Ok
      tags:
      - Balance
  /{auth_path}Odds/ShowAllOdds:
    post:
      operationId: GetOdds
      parameters:
      - description: if user logins, there is no BF
        example: BF
        explode: false
        in: path
        name: auth_path
        required: true
        schema:
          example: BF
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShowAllOddsRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShowAllOddsResponse'
          description: Ok
      tags:
      - Odds
  /{auth_path}main/GetContributor:
    post:
      operationId: GetSports
      parameters:
      - description: if user logins, there is no BF
        example: BF
        explode: false
        in: path
        name: auth_path
        required: true
        schema:
          example: BF
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContributorRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContributorResponse'
          description: Ok
      tags:
      - Odds
components:
  requestBodies:
    inline_object_1:
      content:
        application/x-www-form-urlencoded; charset=UTF-8:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object:
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    ContributorResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
        - GameId: 43
          M0:
            E: 4
            T: 49
            L: 3
            Days:
              "0515": 2
              "0516": 2
            Group:
              "0":
                Days:
                  "0515": 2
                  "0516": 2
                E: 4
                T: 49
                L: 3
              "1":
                Days: {}
                T: 14
                L: 2
              "3":
                Days: {}
                T: 28
              "4":
                Days:
                  "0515": 2
                  "0516": 2
                E: 4
                T: 7
                L: 1
          Name: E-Sports
        - GameId: 1
          M0:
            E: 154
            T: 86
            L: 4
            Days:
              "0515": 48
              "0516": 48
              "0517": 14
              "0518": 1
          Name: Soccer
        - GameId: 2
          M0:
            E: 0
            T: 26
            L: 2
            Days: {}
          Name: Basketball
        - GameId: 8
          M0:
            E: 1
            T: 6
            L: 0
            Days:
              "0516": 1
          Name: Baseball
        - GameId: 5
          M0:
            E: 0
            T: 17
            L: 0
            Days: {}
          Name: Tennis
        - GameId: 18
          M0:
            E: 0
            T: 22
            L: 0
            Days: {}
          Name: Table Tennis
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          items:
            $ref: '#/components/schemas/SportItem'
          type: array
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    ContributorRequest:
      example:
        isParlay: true
        both: true
      properties:
        isParlay:
          type: boolean
        both:
          type: boolean
      required:
      - both
      - isParlay
      type: object
    SportItem:
      example:
        GameId: 2
        M0:
          E: 0
          T: 26
          L: 2
          Days:
            "0515": 2
            "0516": 2
        Name: Basketball
      properties:
        GameId:
          type: integer
        Name:
          type: string
        M0:
          $ref: '#/components/schemas/SportItem_M0'
      required:
      - GameId
      - M0
      - Name
      type: object
    ShowAllOddsRequest:
      example:
        Matchid: 6
        GameId: 0
      properties:
        GameId:
          type: integer
        DateType:
          $ref: '#/components/schemas/DateTypeEnum'
        BetTypeClass:
          $ref: '#/components/schemas/BetTypeClassEnum'
        Matchid:
          type: integer
      required:
      - BetTypeClass
      - DateType
      - GameId
      type: object
    ShowAllOddsResponse:
      example:
        ErrorMsg: ErrorMsg
        Data:
          LeagueN:
            key: LeagueN
          NewMatch:
          - MatchId: 36063550
            Markets:
            - MarketId: 250495469
              MatchId: 36063550
              BetTypeId: 1
              Line: -0.25
              Cat: 0
              Pty: 0
              Pim: false
              Pfm: 2
              Paj: 0
              EXSP: 6.0
              LEXSP: 0.0
              sort: 1
              Selections:
                h:
                  SelId: h
                  Price: 0.88
                  Seq: 0
                a:
                  SelId: a
                  Price: 0.88
                  Seq: 1
            - MarketId: 250769395
              MatchId: 36063550
              BetTypeId: 3
              Line: 5.25
              Cat: 0
              Pty: 0
              Pim: false
              Pfm: 3
              Paj: 0
              EXSP: 4.0
              LEXSP: 0.0
              sort: 2
              Selections:
                h:
                  SelId: h
                  Price: 0.75
                  Seq: 0
                a:
                  SelId: a
                  Price: -0.99
                  Seq: 1
            MatchCode: "001484"
            GameID: 1
            Ktm: 2020-05-14T08:59:00
            ShowTime: Ref_htime
            Etm: 2020-05-14T09:00:00
            LeagueId: 89943
            TeamId1: 675223
            TeamId2: 675221
            IsLive: true
            hasLive: true
            GameTime: 2020-05-14T09:00:00
            T1V: 0
            T2V: 4
            Neu: false
            Moc: 0
            Rc1: 0
            Rc2: 0
            Tsp: false
            LDM: 0
            HLS: 0
            Sup: false
            GV: true
            Sid: "0"
            Src: 0
            MaT: l
            GST: 0
            CCode: others
            Sid2: "0"
            Src2: 0
            FtCount: 2
            HtCount: 2
          - MatchId: 36063550
            Markets:
            - MarketId: 250495469
              MatchId: 36063550
              BetTypeId: 1
              Line: -0.25
              Cat: 0
              Pty: 0
              Pim: false
              Pfm: 2
              Paj: 0
              EXSP: 6.0
              LEXSP: 0.0
              sort: 1
              Selections:
                h:
                  SelId: h
                  Price: 0.88
                  Seq: 0
                a:
                  SelId: a
                  Price: 0.88
                  Seq: 1
            - MarketId: 250769395
              MatchId: 36063550
              BetTypeId: 3
              Line: 5.25
              Cat: 0
              Pty: 0
              Pim: false
              Pfm: 3
              Paj: 0
              EXSP: 4.0
              LEXSP: 0.0
              sort: 2
              Selections:
                h:
                  SelId: h
                  Price: 0.75
                  Seq: 0
                a:
                  SelId: a
                  Price: -0.99
                  Seq: 1
            MatchCode: "001484"
            GameID: 1
            Ktm: 2020-05-14T08:59:00
            ShowTime: Ref_htime
            Etm: 2020-05-14T09:00:00
            LeagueId: 89943
            TeamId1: 675223
            TeamId2: 675221
            IsLive: true
            hasLive: true
            GameTime: 2020-05-14T09:00:00
            T1V: 0
            T2V: 4
            Neu: false
            Moc: 0
            Rc1: 0
            Rc2: 0
            Tsp: false
            LDM: 0
            HLS: 0
            Sup: false
            GV: true
            Sid: "0"
            Src: 0
            MaT: l
            GST: 0
            CCode: others
            Sid2: "0"
            Src2: 0
            FtCount: 2
            HtCount: 2
          TeamN:
            key: TeamN
        ErrorCode: 0
        Syt: 2000-01-23T04:56:07.000+00:00
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Syt:
          format: date-time
          type: string
        Data:
          $ref: '#/components/schemas/ShowAllOddsResponse_Data'
      required:
      - ErrorCode
      - ErrorMsg
      type: object
    EventItem:
      example:
        MatchId: 36063550
        Markets:
        - MarketId: 250495469
          MatchId: 36063550
          BetTypeId: 1
          Line: -0.25
          Cat: 0
          Pty: 0
          Pim: false
          Pfm: 2
          Paj: 0
          EXSP: 6.0
          LEXSP: 0.0
          sort: 1
          Selections:
            h:
              SelId: h
              Price: 0.88
              Seq: 0
            a:
              SelId: a
              Price: 0.88
              Seq: 1
        - MarketId: 250769395
          MatchId: 36063550
          BetTypeId: 3
          Line: 5.25
          Cat: 0
          Pty: 0
          Pim: false
          Pfm: 3
          Paj: 0
          EXSP: 4.0
          LEXSP: 0.0
          sort: 2
          Selections:
            h:
              SelId: h
              Price: 0.75
              Seq: 0
            a:
              SelId: a
              Price: -0.99
              Seq: 1
        MatchCode: "001484"
        GameID: 1
        Ktm: 2020-05-14T08:59:00
        ShowTime: Ref_htime
        Etm: 2020-05-14T09:00:00
        LeagueId: 89943
        TeamId1: 675223
        TeamId2: 675221
        IsLive: true
        hasLive: true
        GameTime: 2020-05-14T09:00:00
        T1V: 0
        T2V: 4
        Neu: false
        Moc: 0
        Rc1: 0
        Rc2: 0
        Tsp: false
        LDM: 0
        HLS: 0
        Sup: false
        GV: true
        Sid: "0"
        Src: 0
        MaT: l
        GST: 0
        CCode: others
        Sid2: "0"
        Src2: 0
        FtCount: 2
        HtCount: 2
      properties:
        GameID:
          type: integer
        LeagueId:
          type: integer
        MatchId:
          type: integer
        TeamId1:
          type: integer
        TeamId2:
          type: integer
        IsLive:
          type: boolean
        hasLive:
          type: boolean
        MatchCode:
          type: string
        GameTime:
          type: string
        Ktm:
          type: string
        ShowTime:
          type: string
        Etm:
          type: string
        T1V:
          type: integer
        T2V:
          type: integer
        Neu:
          type: boolean
        Moc:
          type: integer
        Rc1:
          type: integer
        Rc2:
          type: integer
        Tsp:
          type: boolean
        LDM:
          type: integer
        HLS:
          type: integer
        Sup:
          type: boolean
        GV:
          type: boolean
        Sid:
          type: string
        Sid2:
          type: string
        Src:
          type: integer
        Src2:
          type: integer
        MaT:
          $ref: '#/components/schemas/DateTypeEnum'
        GST:
          type: integer
        CCode:
          type: string
        FtCount:
          type: integer
        HtCount:
          type: integer
        Markets:
          items:
            $ref: '#/components/schemas/MarketItem'
          type: array
      type: object
    MarketItem:
      example:
        MarketId: 250495469
        MatchId: 36063550
        BetTypeId: 1
        Line: -0.25
        Cat: 0
        Pty: 0
        Pim: false
        Pfm: 2
        Paj: 0
        EXSP: 6.0
        LEXSP: 0.0
        sort: 1
        Selections:
          h:
            SelId: h
            Price: 0.88
            Seq: 0
          a:
            SelId: a
            Price: 0.88
            Seq: 1
      properties:
        MarketId:
          type: integer
        MatchId:
          type: integer
        BetTypeId:
          type: integer
        Line:
          format: double
          type: number
        Cat:
          type: integer
        Pty:
          type: integer
        Pim:
          type: boolean
        Pfm:
          type: integer
        Paj:
          type: integer
        EXSP:
          type: number
        LEXSP:
          type: number
        sort:
          type: integer
        IsCP:
          type: boolean
        Selections:
          additionalProperties:
            $ref: '#/components/schemas/SelectionItem'
          type: object
      type: object
    SelectionItem:
      example:
        SelId: h
        Price: 0.88
        Seq: 0
      properties:
        SelId:
          type: string
        Price:
          type: number
        Seq:
          type: integer
      type: object
    DateTypeEnum:
      enum:
      - l
      - t
      - e
      type: string
    BalanceResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
          Name: asdfasdf
          Niname: asdfasdfasdf
          Bal: "200.10"
          OutSd: "0.00"
          NP: "0.00"
          BCredit: "200.10"
          GCredit: "0.00"
          LLogin: 01/01 12:00:00 PM
          LTran: 05/14 02:01:07 PM
          PEdate: 08/20 05:33:16 AM
          ActStatus: 2
          ExtendToken: null
          QualifiedBonus: null
          custBalance:
            finalbalance: 0
            Amount: 0
            Cash: 0
            LockedAmt: 0
          BonusCode: null
          IsShowBonus: false
          NeedGotoDeposit: false
          CustBonus: null
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          $ref: '#/components/schemas/BalanceResponse_Data'
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    TicketsResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
        - TicketType: OU
          Minbet: "1"
          Maxbet: "45"
          Payout: null
          Bet: ""
          QuickBet: 1:100:10:1
          SeqNo: 0
          Line: -0.75
          DisplayHDP: -0.75
          Hdp1: 0.75
          Hdp2: 0
          DisplayOdds: "1.89"
          DisplayOddsPair: "1.85"
          OddsID: 250309593
          Betteam: h
          LiveScore: false
          LiveHomeScore: 0
          LiveAwayScore: 0
          BetID: ""
          ChoiceValue: Getafe CF (V)
          BettypeName: Handicap
          HomeName: Getafe CF (V)
          AwayName: Real Valladolid (V)
          LeagueName: '*SABA SPAIN PRIMERA LALIGA Virtual PES 20 - 15 Mins Play'
          Bettype: "1"
          SportType: 1
          SportName: Soccer
          GameName: ""
          IsLive: false
          IsInPlay: false
          Matchid: 36039171
          MatchCode: null
          Code: 0
          Message: null
          isOddsChange: false
          AutoAcceptSec: ""
          MRPercentage: ""
          OddsInfo: null
          SrcOddsInfo: null
          OddsStatus: null
          PoolType: 0
          UseBonus: 0
          DisplayTime: 11:59 PM
          HasParlay: true
          BonusID: 0
          BonusType: 0
          PromoID: 0
          BetHintMsg: ""
          Common:
            ErrorCode: 0
            ErrorMsg: ""
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          items:
            $ref: '#/components/schemas/TicketItem'
          type: array
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    BetTypeClassEnum:
      enum:
      - OU
      - more
      type: string
    TicketItem:
      example:
        TicketType: OU
        Minbet: "1"
        Maxbet: "45"
        Payout: null
        Bet: ""
        QuickBet: 1:100:10:1
        SeqNo: 0
        Line: -0.75
        DisplayHDP: -0.75
        Hdp1: 0.75
        Hdp2: 0
        DisplayOdds: "1.89"
        DisplayOddsPair: "1.85"
        OddsID: 250309593
        Betteam: h
        LiveScore: false
        LiveHomeScore: 0
        LiveAwayScore: 0
        BetID: ""
        ChoiceValue: Getafe CF (V)
        BettypeName: Handicap
        HomeName: Getafe CF (V)
        AwayName: Real Valladolid (V)
        LeagueName: '*SABA SPAIN PRIMERA LALIGA Virtual PES 20 - 15 Mins Play'
        Bettype: "1"
        SportType: 1
        SportName: Soccer
        GameName: ""
        IsLive: false
        IsInPlay: false
        Matchid: 36039171
        MatchCode: null
        Code: 0
        Message: null
        isOddsChange: false
        AutoAcceptSec: ""
        MRPercentage: ""
        OddsInfo: null
        SrcOddsInfo: null
        OddsStatus: null
        PoolType: 0
        UseBonus: 0
        DisplayTime: 11:59 PM
        HasParlay: true
        BonusID: 0
        BonusType: 0
        PromoID: 0
        BetHintMsg: ""
        Common:
          ErrorCode: 0
          ErrorMsg: ""
      properties:
        TicketType:
          $ref: '#/components/schemas/BetTypeClassEnum'
        Minbet:
          type: string
        Maxbet:
          type: string
        Bet:
          type: string
        QuickBet:
          type: string
        SeqNo:
          type: integer
        Line:
          format: double
          type: number
        DisplayHDP:
          type: string
        Hdp1:
          type: number
        Hdp2:
          type: number
        DisplayOdds:
          type: string
        DisplayOddsPair:
          type: string
        OddsID:
          type: integer
        Betteam:
          type: string
        LiveScore:
          type: boolean
        LiveHomeScore:
          type: integer
        LiveAwayScore:
          type: integer
        BetID:
          type: string
        ChoiceValue:
          type: string
        BettypeName:
          type: string
        HomeName:
          type: string
        AwayName:
          type: string
        LeagueName:
          type: string
        Bettype:
          type: string
        SportType:
          type: integer
        SportName:
          type: string
        GameName:
          type: string
        IsLive:
          type: boolean
        IsInPlay:
          type: boolean
        Matchid:
          type: integer
        Code:
          type: integer
        isOddsChange:
          type: boolean
        AutoAcceptSec:
          type: string
        MRPercentage:
          type: string
        DisplayTime:
          type: string
        HasParlay:
          type: boolean
        BonusID:
          type: integer
        BonusType:
          type: integer
        PromoID:
          type: integer
        BetHintMsg:
          type: string
        Common:
          $ref: '#/components/schemas/CommonItem'
      type: object
    TicketsRequest:
      example:
        ItemList[0][type]: OU
        ItemList[0][bettype]: 1
        ItemList[0][oddsid]: 250309593
        ItemList[0][odds]: 1.89
        ItemList[0][Line]: -0.75
        ItemList[0][Hscore]: 0
        ItemList[0][Ascore]: 0
        ItemList[0][Matchid]: 36039171
        ItemList[0][betteam]: h
        ItemList[0][stake]: 0
        ItemList[0][QuickBet]: 1:100:10:1
        ItemList[0][ChoiceValue]: 0
        ItemList[0][home]: Getafe CF (V)
        ItemList[0][away]: Real Valladolid (V)
        ItemList[0][gameid]: 1
        ItemList[0][MRPercentage]: null
        ItemList[0][GameName]: null
        ItemList[0][SportName]: null
        ItemList[0][IsInPlay]: false
        ItemList[0][SrcOddsInfo]: null
        ItemList[0][pty]: 0
        ItemList[0][hdp1]: 0.75
        ItemList[0][hdp2]: 0
        ItemList[0][BonusID]: null
      properties:
        ItemList[0][type]:
          $ref: '#/components/schemas/BetTypeClassEnum'
        ItemList[0][bettype]:
          type: integer
        ItemList[0][oddsid]:
          type: integer
        ItemList[0][odds]:
          type: number
        ItemList[0][Line]:
          format: double
          type: number
        ItemList[0][Hscore]:
          type: integer
        ItemList[0][Ascore]:
          type: integer
        ItemList[0][Matchid]:
          type: integer
        ItemList[0][betteam]:
          type: string
        ItemList[0][stake]:
          type: integer
        ItemList[0][QuickBet]:
          type: string
        ItemList[0][ChoiceValue]:
          type: string
        ItemList[0][home]:
          type: string
        ItemList[0][away]:
          type: string
        ItemList[0][gameid]:
          type: integer
        ItemList[0][IsInPlay]:
          type: boolean
        ItemList[0][pty]:
          type: integer
        ItemList[0][hdp1]:
          type: number
        ItemList[0][hdp2]:
          type: number
      required:
      - ItemList[0][betteam]
      - ItemList[0][oddsid]
      - ItemList[0][type]
      type: object
    PlaceBetRequest:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
          ItemList:
          - Key: 250021354_h
            DisplayOdds: "1.97"
            DisplayHDP: "0.25"
            Hdp1: 0
            Hdp2: 0.25
            OddsInfo: null
            SrcOddsInfo: null
            BetID: ""
            TransId_Cash: "109034866899"
            TransId_Bonus: "0"
            Code: 1
            Message: Your bet has been accepted.
            isOddsChange: false
            Stake: "1"
            Stake_Cash: "1.00"
            Stake_Bonus: "0.00"
            ActualStake_Cash: "1.00"
            ActualStake_Bonus: "0.00"
            LiveHomeScore: 0
            LiveAwayScore: 0
            TicketStatus: 1
            IsInPlay: false
            TotalPerBet: 0
            FinalBalance: "199.10"
            CheckWaitingTicket: false
            ErrorCode: 0
            TicketJson: null
            BetRecommendation:
            - matchid: 36003476
              sporttype: 0
              kickofftime: null
            Common:
              ErrorCode: 0
              ErrorMsg: null
          ErrorMsg: null
          Common:
            ErrorCode: 0
            ErrorMsg: null
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          $ref: '#/components/schemas/PlaceBetRequest_Data'
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    CommonItem:
      example:
        ErrorCode: 0
        ErrorMsg: null
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
      required:
      - ErrorCode
      type: object
    PlaceBetItem:
      example:
        Key: 250021354_h
        DisplayOdds: "1.97"
        DisplayHDP: "0.25"
        Hdp1: 0
        Hdp2: 0.25
        OddsInfo: null
        SrcOddsInfo: null
        BetID: ""
        TransId_Cash: "109034866899"
        TransId_Bonus: "0"
        Code: 1
        Message: Your bet has been accepted.
        isOddsChange: false
        Stake: "1"
        Stake_Cash: "1.00"
        Stake_Bonus: "0.00"
        ActualStake_Cash: "1.00"
        ActualStake_Bonus: "0.00"
        LiveHomeScore: 0
        LiveAwayScore: 0
        TicketStatus: 1
        IsInPlay: false
        TotalPerBet: 0
        FinalBalance: "199.10"
        CheckWaitingTicket: false
        ErrorCode: 0
        TicketJson: null
        BetRecommendation:
        - matchid: 36003476
          sporttype: 0
          kickofftime: null
        Common:
          ErrorCode: 0
          ErrorMsg: null
      properties:
        Key:
          type: string
        DisplayOdds:
          type: string
        DisplayHDP:
          type: string
        Hdp1:
          type: number
        Hdp2:
          type: number
        BetID:
          type: string
        TransId_Cash:
          type: string
        TransId_Bonus:
          type: string
        Code:
          type: integer
        Message:
          type: string
        isOddsChange:
          type: boolean
        Stake:
          type: string
        Stake_Cash:
          type: string
        LiveHomeScore:
          type: integer
        LiveAwayScore:
          type: integer
        TicketStatus:
          type: integer
        IsInPlay:
          type: boolean
        TotalPerBet:
          type: integer
        FinalBalance:
          type: string
        CheckWaitingTicket:
          type: boolean
        ErrorCode:
          type: integer
        Common:
          $ref: '#/components/schemas/CommonItem'
      type: object
    BetStatusResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
          status: running
          ReasonID: null
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          $ref: '#/components/schemas/BetStatusResponse_Data'
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    GetMarketsResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data:
          Markets:
            NewOdds:
            - MarketId: 250021348
              MatchId: 36003476
              BetTypeId: 2
              Line: 0.0
              Cat: 1
              Pty: 0
              Pim: true
              Pfm: 3
              Paj: 0
              EXSP: 0.0
              LEXSP: 0.0
              sort: 1
              IsCP: false
              Selections:
                h:
                  SelId: h
                  Price: 0.94
                  Seq: 0
                a:
                  SelId: a
                  Price: 0.94
                  Seq: 1
            - MarketId: 250021339
              MatchId: 36003476
              BetTypeId: 5
              Line: 0.08
              Cat: 0
              Pty: 1
              Pim: true
              Pfm: 0
              Paj: 0
              EXSP: 0.0
              LEXSP: 0.0
              sort: 1
              IsCP: false
              Selections:
                "1":
                  SelId: "1"
                  Price: 3.2
                  Seq: 0
                x:
                  SelId: x
                  Price: 3.3
                  Seq: 1
                "2":
                  SelId: "2"
                  Price: 2.15
                  Seq: 2
          SpMatch:
            NewMatch: []
            TeamN: {}
            LeagueN: {}
        Syt: 2020-05-14T14:47:09.0632376-04:00
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          $ref: '#/components/schemas/GetMarketsResponse_Data'
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    AuthenticateRequest:
      properties:
        username:
          type: string
        password:
          type: string
      type: object
    AuthenticateResponse:
      example:
        success: true
        matrix: true
        hash: hash
        token: token
      properties:
        success:
          type: boolean
        hash:
          type: string
        token:
          type: string
        matrix:
          type: boolean
      type: object
    CheckTokenResponse:
      example:
        token: hhhhhhhhhhhhhhhhhhhhhhh
        rid: 0
        id: 0
        url: hhhhhhhhh.net
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        token:
          type: string
        rid:
          type: integer
        id:
          type: integer
        url:
          type: string
      type: object
    RunningBetListResponse:
      example:
        Ticket: Ticket
        StakeCount: StakeCount
        TicketCount: 0
      properties:
        StakeCount:
          type: string
        TicketCount:
          type: integer
        Ticket:
          type: string
      required:
      - StakeCount
      - Ticket
      - TicketCount
      type: object
    GetAccountResponse:
      example:
        ErrorCode: 0
        ErrorMsg: ""
        Data: {}
      properties:
        ErrorCode:
          type: integer
        ErrorMsg:
          type: string
        Data:
          $ref: '#/components/schemas/AccountInfo'
      required:
      - Data
      - ErrorCode
      - ErrorMsg
      type: object
    SetOddsTypeResponse:
      example:
        ErrorCode: 0
        Data:
          OddsType: 1
      properties:
        ErrorCode:
          type: integer
        Data:
          $ref: '#/components/schemas/SetOddsTypeResponse_Data'
      required:
      - Data
      - ErrorCode
      type: object
    AccountInfo:
      example:
        Cas: 0
        SyncCasino: false
        LCas: 0
        NG: 1
        VR: 1
        RC: 0
        GD: 0
        SL: 0
        MT: 1
        CF: 0
        CB: 1
        BF: 0
        PG: 0
        N7: 0
        SysT: 2020,6,15,13,41,11,+8
        Lang: en-US
        Curr: USD (United States Dollar)
        OType: 1
        SYT: 1
        Spread: 0.0
        LB: null
        MR: 0
        CHP: 0
        UT: 0
        HP: 0
        QK: 1
        QBS: null
        CL: 0
        RNGJP: 0
        UserReject: false
        CS: true
        CSByRef: false
        VsPlace: true
        ID: 3236931
        AllBet: true
        SAGaming: 0
        LoginUserName: asfdasdf
        Keno: 1
        CO: 1
        KL: 1
        VRS: 1
        VSAC: 1
        Exchange: 1
        TransFd: false
        SLOut: false
        AG: 0
        SMP: true
        BetterOdds: true
        CustSeq: 0
        AccessToken: null
        RefreshToken: null
        BankingUrl: null
        CurrId: 3
        VRG: true
        Indo4D: false
        SXG: false
        SC: false
        VSEP: 0
        VSCC: 1
        VSEC: 1
        BLC: 0
        OneRng: 0
        MiniStatus: 0
        SpadeGaming: 0
        VBStatus: 0
        PPStatus: 0
        TG: 1
        GG: 0
        SOC: 0
        RNGWar: 0
        ION: 0
        Name: SPONUUS01001
        Niname: ""
        Bal: "0.00"
        OutSd: "0.00"
        NP: "0.00"
        BCredit: "0.00"
        GCredit: "0.00"
        LLogin: 0001/01/01 12:00:00 PM
        LTran: 2020/06/15 01:41:11 PM
        PEdate: 2010/12/05 02:47:43 AM
        ActStatus: 1
        ExtendToken: 917sdfgdsfgsdfgsfgfgsde5
        QualifiedBonus: null
        custBalance: null
        BonusCode: null
        IsShowBonus: false
        NeedGotoDeposit: false
        CustBonus: null
      properties:
        LoginUserName:
          type: string
      type: object
    inline_object:
      properties:
        datatype:
          example: 0
          type: integer
      type: object
    inline_object_1:
      properties:
        fdate:
          example: 05/17/2020
          type: string
        datatype:
          example: 8
          type: integer
      type: object
    SportItem_M0:
      properties:
        E:
          type: integer
        T:
          type: integer
        L:
          type: integer
        Days:
          additionalProperties:
            type: integer
          type: object
      required:
      - E
      - L
      - T
    ShowAllOddsResponse_Data:
      example:
        LeagueN:
          key: LeagueN
        NewMatch:
        - MatchId: 36063550
          Markets:
          - MarketId: 250495469
            MatchId: 36063550
            BetTypeId: 1
            Line: -0.25
            Cat: 0
            Pty: 0
            Pim: false
            Pfm: 2
            Paj: 0
            EXSP: 6.0
            LEXSP: 0.0
            sort: 1
            Selections:
              h:
                SelId: h
                Price: 0.88
                Seq: 0
              a:
                SelId: a
                Price: 0.88
                Seq: 1
          - MarketId: 250769395
            MatchId: 36063550
            BetTypeId: 3
            Line: 5.25
            Cat: 0
            Pty: 0
            Pim: false
            Pfm: 3
            Paj: 0
            EXSP: 4.0
            LEXSP: 0.0
            sort: 2
            Selections:
              h:
                SelId: h
                Price: 0.75
                Seq: 0
              a:
                SelId: a
                Price: -0.99
                Seq: 1
          MatchCode: "001484"
          GameID: 1
          Ktm: 2020-05-14T08:59:00
          ShowTime: Ref_htime
          Etm: 2020-05-14T09:00:00
          LeagueId: 89943
          TeamId1: 675223
          TeamId2: 675221
          IsLive: true
          hasLive: true
          GameTime: 2020-05-14T09:00:00
          T1V: 0
          T2V: 4
          Neu: false
          Moc: 0
          Rc1: 0
          Rc2: 0
          Tsp: false
          LDM: 0
          HLS: 0
          Sup: false
          GV: true
          Sid: "0"
          Src: 0
          MaT: l
          GST: 0
          CCode: others
          Sid2: "0"
          Src2: 0
          FtCount: 2
          HtCount: 2
        - MatchId: 36063550
          Markets:
          - MarketId: 250495469
            MatchId: 36063550
            BetTypeId: 1
            Line: -0.25
            Cat: 0
            Pty: 0
            Pim: false
            Pfm: 2
            Paj: 0
            EXSP: 6.0
            LEXSP: 0.0
            sort: 1
            Selections:
              h:
                SelId: h
                Price: 0.88
                Seq: 0
              a:
                SelId: a
                Price: 0.88
                Seq: 1
          - MarketId: 250769395
            MatchId: 36063550
            BetTypeId: 3
            Line: 5.25
            Cat: 0
            Pty: 0
            Pim: false
            Pfm: 3
            Paj: 0
            EXSP: 4.0
            LEXSP: 0.0
            sort: 2
            Selections:
              h:
                SelId: h
                Price: 0.75
                Seq: 0
              a:
                SelId: a
                Price: -0.99
                Seq: 1
          MatchCode: "001484"
          GameID: 1
          Ktm: 2020-05-14T08:59:00
          ShowTime: Ref_htime
          Etm: 2020-05-14T09:00:00
          LeagueId: 89943
          TeamId1: 675223
          TeamId2: 675221
          IsLive: true
          hasLive: true
          GameTime: 2020-05-14T09:00:00
          T1V: 0
          T2V: 4
          Neu: false
          Moc: 0
          Rc1: 0
          Rc2: 0
          Tsp: false
          LDM: 0
          HLS: 0
          Sup: false
          GV: true
          Sid: "0"
          Src: 0
          MaT: l
          GST: 0
          CCode: others
          Sid2: "0"
          Src2: 0
          FtCount: 2
          HtCount: 2
        TeamN:
          key: TeamN
      properties:
        LeagueN:
          additionalProperties:
            type: string
          type: object
        TeamN:
          additionalProperties:
            type: string
          type: object
        NewMatch:
          items:
            $ref: '#/components/schemas/EventItem'
          type: array
    BalanceResponse_Data:
      properties:
        Name:
          type: string
        Niname:
          type: string
        Bal:
          type: string
        OutSd:
          type: string
        NP:
          type: string
        BCredit:
          type: string
        GCredit:
          type: string
        LLogin:
          type: string
        LTran:
          type: string
        PEdate:
          type: string
        ActStatus:
          type: integer
    PlaceBetRequest_Data:
      properties:
        ItemList:
          items:
            $ref: '#/components/schemas/PlaceBetItem'
          type: array
        ErrorMsg:
          type: string
        Common:
          $ref: '#/components/schemas/CommonItem'
    BetStatusResponse_Data:
      properties:
        status:
          type: string
        ReasonID:
          type: integer
      required:
      - status
    GetMarketsResponse_Data_Markets:
      properties:
        NewOdds:
          items:
            $ref: '#/components/schemas/MarketItem'
          type: array
    GetMarketsResponse_Data:
      properties:
        SpMatch:
          $ref: '#/components/schemas/ShowAllOddsResponse_Data'
        NewOdds:
          items:
            $ref: '#/components/schemas/MarketItem'
          type: array
        Markets:
          $ref: '#/components/schemas/GetMarketsResponse_Data_Markets'
    SetOddsTypeResponse_Data:
      properties:
        OddsType:
          type: integer
  securitySchemes:
    x-session:
      in: header
      name: Cookie
      type: apiKey
